const CONSTANTS = {
  API_BASE: '10.1.131.46:5001/api',
  SOCKET_EVENT_NOTIFICATION: 'NEW_NOTIFICATION',
  IPv4_ADDRESS: '10.1.131.46',
  SOCKET_REFRESH_TASK_LIST: 'SOCKET_REFRESH_TASK_LIST'
}

export default CONSTANTS;