DELETE http://localhost:5001/api/tasks/666c672e49eb1d02c4882464 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiMWVmMzA3ZmEyMjY2M2M0MDIwYWUiLCJlbWFpbCI6ImphbmUuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxODk4NTk1OSwiZXhwIjoxNzE4OTg2MDE5fQ.2IafIpppzDufN6Vj4_dbeajUmCvx_OjWkLw5B375lBc